const ADD_MENU_ITEM_FETCH_REQUEST = '[menuItem_add] FETCH_REQUEST';
const ADD_MENU_ITEM_FETCH_SUCCESS = '[menuItem_add] FETCH_SUCCESS';
const ADD_MENU_ITEM_FETCH_ERROR = '[menuItem_add] FETCH_ERROR';

const BUFFER_DISH_LIST_CLEAR = '[menuItem_add] BUFFER_CLEAR';

export default {
  ADD_MENU_ITEM_FETCH_REQUEST,
  ADD_MENU_ITEM_FETCH_SUCCESS,
  ADD_MENU_ITEM_FETCH_ERROR,
  BUFFER_DISH_LIST_CLEAR,
};
