const MENU_ITEM_COMMENT_FETCH_REQUEST = '[menuItem] COMMENT_FETCH_REQUEST';
const MENU_ITEM_COMMENT_FETCH_SUCCESS = '[menuItem] COMMENT_FETCH_SUCCESS';
const MENU_ITEM_COMMENT_FETCH_ERROR = '[menuItem] COMMENT_FETCH_ERROR';
export default {
  MENU_ITEM_COMMENT_FETCH_REQUEST,
  MENU_ITEM_COMMENT_FETCH_SUCCESS,
  MENU_ITEM_COMMENT_FETCH_ERROR,
};
